In [3]:
import numpy as np

In [24]:
num=0

# txt_path="./data/txt/test_label.txt"
label_path="./result/%s/txt/test_pred.txt"%str(num)

f=open(label_path,"r")
labels=f.readlines()
f.close()

y_test=[]
pred_label=[]
for i in range(len(labels)):
    try:
        file=labels[i].split(',')[0]
        t_clas=file.split('/')[-1][0] # A,N,P
        p_clas=labels[i].split(',')[-1] # atypical, normal,positive
                
        y_test.append(t_clas)
        pred_label.append(p_clas)
        
    except:
        print(labels[i])

for i in range(len(pred_label)):
    if pred_label[i]=='normal\n' or pred_label[i]=='noraml\n':
        pred_label[i]=0
        
    elif pred_label[i]=='atypical\n':
        pred_label[i]=1
    
    elif pred_label[i]=='positive\n':
        pred_label[i]=2
        
for i in range(len(y_test)):
    if y_test[i]=='N':
        y_test[i]=0
        
    elif y_test[i]=='A':
        y_test[i]=1
    
    elif y_test[i]=='P':
        y_test[i]=2
        
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from keras.preprocessing.image import array_to_img
from keras.models import Model, load_model


cm=confusion_matrix(y_test,pred_label)
print(cm)
acc=accuracy_score(y_test,pred_label)
print("acc=",acc)

print(cm[0][0]/(cm[0][0]+cm[0][1]+cm[0][2]))
print(cm[1][1]/(cm[1][0]+cm[1][1]+cm[1][2]))
print(cm[2][2]/(cm[2][0]+cm[2][1]+cm[2][2]))

In [27]:
for i in range(len(pred_label)):
    if pred_label[i]=='normal\n' or pred_label[i]=='noraml\n':
        pred_label[i]=0
        
    elif pred_label[i]=='atypical\n':
        pred_label[i]=1
    
    elif pred_label[i]=='positive\n':
        pred_label[i]=2

In [28]:
for i in range(len(y_test)):
    if y_test[i]=='N':
        y_test[i]=0
        
    elif y_test[i]=='A':
        y_test[i]=1
    
    elif y_test[i]=='P':
        y_test[i]=2

In [29]:
y_test

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from keras.preprocessing.image import array_to_img
from keras.models import Model, load_model


cm=confusion_matrix(y_test,pred_label)
print(cm)
acc=accuracy_score(y_test,pred_label)
print("acc=",acc)

print(cm[0][0]/(cm[0][0]+cm[0][1]+cm[0][2]))
print(cm[1][1]/(cm[1][0]+cm[1][1]+cm[1][2]))
print(cm[2][2]/(cm[2][0]+cm[2][1]+cm[2][2]))

[[ 57 332  12]
 [ 28 769  41]
 [  1 235 191]]
acc= 0.6104441776710684
0.14214463840399003
0.9176610978520287
0.44730679156908665
